image: python:2.7

stages:
  - test
  - deploy

unit_test:
  stage: test
  script:
    - pip install -r test-requirements.txt
    - tox -e flake8
    - pip install .
    - vca --version
    - vcd version
  except:
    - tags

deploy:
  stage: deploy
  script:
    - pip install twine
    - rm -rf build dist
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  except:
    - tags
  dependencies:
    - unit_test
