language: python

python:
  - '3.6'

install:
  - python --version
  - pip install -r requirements.txt
  - python setup.py install
  - pip install tox

script:
  - pip list --format=columns | grep pyvcloud
  - python -c 'import pkg_resources; print(pkg_resources.require("pyvcloud")[0].version)'
  - tox -e flake8
